[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
[headers.values]
  Cache-Control = "public, max-age=360000" 